repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch # prevent direct commits to the `main` branch
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: npm-install
        name: format install
        entry: npm
        args: [install]
        language: system
        types_or: [json]
        pass_filenames: false
      - id: format-ts
        name: format typescript
        entry: make
        args: [format-ts]
        language: system
        types_or: [javascript, ts, json]
        pass_filenames: false
      - id: typecheck-ts
        name: typecheck typescript
        entry: make
        args: [typecheck-ts]
        language: system
        types_or: [javascript, ts, json]
        pass_filenames: false
      - id: format-py
        name: format python
        entry: make
        args: [format-py]
        language: system
        types: [python]
        pass_filenames: false
      - id: typecheck-py
        name: typecheck python
        entry: make
        args: [typecheck-py]
        language: system
        types: [python]
        pass_filenames: false
